<option value="AnimalRescue">Animal Rescue</option>
<option value="AddictionDrugs">Addiction/Drugs</option>
<option value="ALS">ALS</option>
<option value="AntiBullying">Anti-Bullying</option>
<option value="ArtsandCulture">Arts and Culture</option>
<option value="Autism">Autism</option>
<option value="Camps">Camps</option>
<option value="Cancer">Cancer</option>
<option value="ChildrensHealth">Children's Health</option>
<option value="CleanWaterEnergy">Clean Water/Energy</option>
<option value="Clothing">Clothing</option>
<option value="Diabetes">Diabetes</option>
<option value="DisasterRelief">Disaster Relief</option>
<option value="DrunkDriving">Drunk Driving</option>
<option value="Education">Education</option>
<option value="Environment">Environment</option>
<option value="HealthAndFitness">Health & Fitness</option>
<option value="HeartDisease">Heart Disease</option>
<option value="Homelessness">Homelessness</option>
<option value="Housing">Housing</option>
<option value="HumanRights">Human Rights</option>
<option value="MentalHealth">Mental Health</option>
<option value="ParkinsonsDisease">Parkinson's Disease</option>
<option value="Veterans">Veterans</option>
