<option value="AmericanFootball">American Football</option>
<option value="BaseballAndSoftball">Baseball & Softball</option>
<option value="Basketball">Basketball</option>
<option value="Cheerleading">Cheerleading</option>
<option value="Crew">Crew</option>
<option value="Cycling">Cycling</option>
<option value="Dance">Dance</option>
<option value="Dodgeball">Dodgeball</option>
<option value="Football">Football</option>
<option value="Golf">Golf</option>
<option value="Gymnastics">Gymnastics</option>
<option value="Hockey">Hockey</option>
<option value="Lacrosse">Lacrosse</option>
<option value="MartialArts">Martial Arts</option>
<option value="Rugby">Rugby</option>
<option value="SkiingAndSnowboarding">Skiing & Snowboarding</option>
<option value="Swimming">Swimming</option>
<option value="Tennis">Tennis</option>
<option value="TrackRunning">Track/Running</option>
<option value="UltimateFrisbee">Ultimate Frisbee</option>
<option value="Volleyball">Volleyball</option>
<option value="WaterPolo">Water Polo</option>
<option value="Wrestling">Wrestling</option>
