<option value="AgaKhanUniversity">Aga Khan University</option>
<option value="AmericanInterContinentalUniversityLondon">American InterContinental University - London</option>
<option value="AngliaRuskinUniversity">Anglia Ruskin University</option>
<option value="AstonUniversity">Aston University</option>
<option value="BirkbeckCollege,UniversityofLondon">Birkbeck College, University of London</option>
<option value="BirminghamCityUniversity">Birmingham City University</option>
<option value="BournemouthUniversity">Bournemouth University</option>
<option value="BritishCollegeofOsteopathicMedicine">British College of Osteopathic Medicine</option>
<option value="BrunelUniversityUxbridge">Brunel University Uxbridge</option>
<option value="BuckinghamshireNewUniversity">Buckinghamshire New University</option>
<option value="CamberwellCollegeofArts">Camberwell College of Arts</option>
<option value="CanterburyChristChurchUniversity">Canterbury Christ Church University</option>
<option value="CardiffUniversity">Cardiff University</option>
<option value="CentralSaintMartinsCollegeofArtDesign">Central Saint Martins College of Art & Design</option>
<option value="ChelseaCollegeofArtandDesign">Chelsea College of Art and Design</option>
<option value="CityUniversity">City University</option>
<option value="CourtauldInstituteofArt,UniversityofLondon">Courtauld Institute of Art, University of London</option>
<option value="CoventryUniversity">Coventry University</option>
<option value="CranfieldUniversity">Cranfield University</option>
<option value="DeMontfortUniversityLeicester">De Montfort University Leicester</option>
<option value="EuropeanSchoolofEconomics">European School of Economics</option>
<option value="FalmouthUniversity">Falmouth University</option>
<option value="GlasgowCaledonianUniversity">Glasgow Caledonian University</option>
<option value="GlasgowSchoolofArt">Glasgow School of Art</option>
<option value="GoldsmithsCollege,UniversityofLondon">Goldsmiths College, University of London</option>
<option value="HeriotWattUniversity">Heriot-Watt University</option>
<option value="HeythropCollege,UniversityofLondon">Heythrop College, University of London</option>
<option value="HuronUniversityUSAinLondon">Huron University USA in London</option>
<option value="ifsUniversityCollege">ifs University College</option>
<option value="ImperialCollegeLondon">Imperial College London</option>
<option value="ImperialCollegeSchoolofMedicine">Imperial College School of Medicine</option>
<option value="InstitueofHistoricalResearch,UniversityofLondon">Institue of Historical Research, University of London</option>
<option value="InstituteofAdvancedLegalStudies,UniversityofLondon">Institute of Advanced Legal Studies, University of London</option>
<option value="InstituteofClassicalStudies,UniversityofLondon">Institute of Classical Studies, University of London</option>
<option value="InstituteofCommonwealthStudies,UniversityofLondon">Institute of Commonwealth Studies, University of London</option>
<option value="InstituteofEducation,UniversityofLondon">Institute of Education, University of London</option>
<option value="InstituteofGermanicStudies,UniversityofLondon">Institute of Germanic Studies, University of London</option>
<option value="InstituteofLatinAmericanStudies,UniversityofLondon">Institute of Latin American Studies, University of London</option>
<option value="InternationalCentreforIsclamicScience">International Centre for Isclamic Science</option>
<option value="InternationalCollegesofIslamicScience">International Colleges of Islamic Science</option>
<option value="KeeleUniversity">Keele University</option>
<option value="KingsCollegeLondon,UniversityofLondon">King's College London, University of London</option>
<option value="KingstonUniversity">Kingston University</option>
<option value="LeedsMetropolitanUniversity">Leeds Metropolitan University</option>
<option value="LiverpoolHopeUniversityCollege">Liverpool Hope University College</option>
<option value="LiverpoolJohnMooresUniversity">Liverpool John Moores University</option>
<option value="LondonBusinessSchool">London Business School</option>
<option value="LondonCollegeofScienceTechnology">London College of Science & Technology</option>
<option value="LondonGuildhallUniversity">London Guildhall University</option>
<option value="LondonInstituteofManagementandTechnology">London Institute of Management and Technology</option>
<option value="LondonMetropolitanUniversity">London Metropolitan University</option>
<option value="LondonSchoolofBusinessFinance">London School of Business & Finance</option>
<option value="LondonSchoolofEconomicsandPoliticalScience,UniversityofLondon">London School of Economics and Political Science, University of London</option>
<option value="LondonSchoolofHygieneTropicalMedicine,UniversityofLondon">London School of Hygiene & Tropical Medicine, University of London</option>
<option value="LondonSchoolofJewishStudies">London School of Jewish Studies</option>
<option value="LoughboroughUniversity">Loughborough University</option>
<option value="MiddlesexUniversity">Middlesex University</option>
<option value="NapierUniversity">Napier University</option>
<option value="NewportInternationalUniversity">Newport International University</option>
<option value="NottinghamTrentUniversity">Nottingham Trent University</option>
<option value="OpenUniversity">Open University</option>
<option value="OxfordBrookesUniversity">Oxford Brookes University</option>
<option value="QueenMaryandWestfieldCollege,UniversityofLondon">Queen Mary and Westfield College, University of London</option>
<option value="RichmondUniversityTheAmericanInternationalUniversityinLondon">Richmond University - The American International University in London</option>
<option value="RoehamptonUniversityofSurrey">Roehampton University of Surrey</option>
<option value="RoyalAcademyofMusic,UniversityofLondon">Royal Academy of Music, University of London</option>
<option value="RoyalCollegeofArt">Royal College of Art</option>
<option value="RoyalCollegeofMusic,UniversityofLondon">Royal College of Music, University of London</option>
<option value="RoyalFreeHospitalSchoolofMedicine,UniversityofLondon">Royal Free Hospital School of Medicine, University of London</option>
<option value="RoyalHollowayandBedfordNewCollege">Royal Holloway and Bedford New College</option>
<option value="SaintGeorgesHospitalMedicalSchool,UniversityofLondon">Saint George's Hospital Medical School, University of London</option>
<option value="SchillerInternationalUniversity,London">Schiller International University, London</option>
<option value="SchoolofOrientalandAfricanStudies,UniversityofLondon">School of Oriental and African Studies, University of London</option>
<option value="SchoolofPharmacy,UniversityofLondon">School of Pharmacy, University of London</option>
<option value="SchoolofSlavonicandEastEuropeanStudies,UniversityofLondon">School of Slavonic and East European Studies, University of London</option>
<option value="SheffieldHallamUniversity">Sheffield Hallam University</option>
<option value="Sotheby´sInstituteofArtLondon">Sotheby´s Institute of Art - London</option>
<option value="SouthamptonSolentUniversity">Southampton Solent University</option>
<option value="SouthBankUniversity">South Bank University</option>
<option value="StaffordshireUniversity">Staffordshire University</option>
<option value="St.PatricksInternationalCollege,London">St.Patrick's International College, London</option>
<option value="StratfordCollegeLondon">Stratford College London</option>
<option value="SwanseaMetropolitanUniversity">Swansea Metropolitan University</option>
<option value="ThamesValleyUniversity">Thames Valley University</option>
<option value="TheAmericanUniversityinLondon">The American University in London</option>
<option value="TheManchesterMetropolitanUniversity">The Manchester Metropolitan University</option>
<option value="TheQueensUniversityBelfast">The Queen's University Belfast</option>
<option value="TheRobertGordonUniversity">The Robert Gordon University</option>
<option value="TrinityCollegeCarmarthen">Trinity College Carmarthen</option>
<option value="TrinityCollegeofMusic">Trinity College of Music</option>
<option value="UnitedMedicalandDentalSchools,UniversityofLondon">United Medical and Dental Schools, University of London</option>
<option value="UniversityCampusSuffolk">University Campus Suffolk</option>
<option value="UniversityCollegeLondon,UniversityofLondon">University College London, University of London</option>
<option value="UniversityofAberdeen">University of Aberdeen</option>
<option value="UniversityofAbertayDundee">University of Abertay Dundee</option>
<option value="UniversityofBath">University of Bath</option>
<option value="UniversityofBedfordshire">University of Bedfordshire</option>
<option value="UniversityofBirmingham">University of Birmingham</option>
<option value="UniversityofBolton">University of Bolton</option>
<option value="UniversityofBradford">University of Bradford</option>
<option value="UniversityofBrighton">University of Brighton</option>
<option value="UniversityofBristol">University of Bristol</option>
<option value="UniversityofBuckingham">University of Buckingham</option>
<option value="UniversityofCambridge">University of Cambridge</option>
<option value="UniversityofCentralLancashire">University of Central Lancashire</option>
<option value="UniversityofChester">University of Chester</option>
<option value="UniversityofDerby">University of Derby</option>
<option value="UniversityofDundee">University of Dundee</option>
<option value="UniversityofDurham">University of Durham</option>
<option value="UniversityofEastAnglia">University of East Anglia</option>
<option value="UniversityofEastLondon">University of East London</option>
<option value="UniversityofEdinburgh">University of Edinburgh</option>
<option value="UniversityofEssex">University of Essex</option>
<option value="UniversityofExeter">University of Exeter</option>
<option value="UniversityofGlamorgan">University of Glamorgan</option>
<option value="UniversityofGlasgow">University of Glasgow</option>
<option value="UniversityofGloucestershire">University of Gloucestershire</option>
<option value="UniversityofGreenwich">University of Greenwich</option>
<option value="UniversityofHalifax,BirminghamCampus">University of Halifax, Birmingham Campus</option>
<option value="UniversityofHertfordshire">University of Hertfordshire</option>
<option value="UniversityofHuddersfield">University of Huddersfield</option>
<option value="UniversityofHull">University of Hull</option>
<option value="UniversityofKentatCanterbury">University of Kent at Canterbury</option>
<option value="UniversityofLancaster">University of Lancaster</option>
<option value="UniversityofLeeds">University of Leeds</option>
<option value="UniversityofLeicester">University of Leicester</option>
<option value="UniversityofLincoln">University of Lincoln</option>
<option value="UniversityofLiverpool">University of Liverpool</option>
<option value="UniversityofLondon">University of London</option>
<option value="UniversityofManchester">University of Manchester</option>
<option value="UniversityofNewcastleuponTyne">University of Newcastle-upon-Tyne</option>
<option value="UniversityofNorthampton">University of Northampton</option>
<option value="UniversityofNorthLondon">University of North London</option>
<option value="UniversityofNorthumbriaatNewcastle">University of Northumbria at Newcastle</option>
<option value="UniversityofNottingham">University of Nottingham</option>
<option value="UniversityofOxford">University of Oxford</option>
<option value="UniversityofPaisley">University of Paisley</option>
<option value="UniversityofPlymouth">University of Plymouth</option>
<option value="UniversityofPortsmouth">University of Portsmouth</option>
<option value="UniversityofReading">University of Reading</option>
<option value="UniversityofSalford">University of Salford</option>
<option value="UniversityofSheffield">University of Sheffield</option>
<option value="UniversityofSouthampton">University of Southampton</option>
<option value="UniversityofSt.Andrews">University of St. Andrews</option>
<option value="UniversityofStirling">University of Stirling</option>
<option value="UniversityofStrathclyde">University of Strathclyde</option>
<option value="UniversityofSunderland">University of Sunderland</option>
<option value="UniversityofSurrey">University of Surrey</option>
<option value="UniversityofSussex">University of Sussex</option>
<option value="UniversityofTeesside">University of Teesside</option>
<option value="UniversityoftheWestofEngland,Bristol">University of the West of England, Bristol</option>
<option value="UniversityofUlster">University of Ulster</option>
<option value="UniversityofWales">University of Wales</option>
<option value="UniversityofWales,Aberystwyth">University of Wales, Aberystwyth</option>
<option value="UniversityofWales,Bangor">University of Wales, Bangor</option>
<option value="UniversityofWalesCollegeofMedicine">University of Wales College of Medicine</option>
<option value="UniversityofWalesInstitute,Cardiff">University of Wales Institute, Cardiff</option>
<option value="UniversityofWales,Lampeter">University of Wales, Lampeter</option>
<option value="UniversityofWales,Newport">University of Wales, Newport</option>
<option value="UniversityofWales,Swansea">University of Wales, Swansea</option>
<option value="UniversityofWarwick">University of Warwick</option>
<option value="UniversityofWestminster">University of Westminster</option>
<option value="UniversityofWolverhampton">University of Wolverhampton</option>
<option value="UniversityofWorcester">University of Worcester</option>
<option value="UniversityofYork">University of York</option>
<option value="WarburgInstitute,UniversityofLondon">Warburg Institute, University of London</option>
<option value="WarnboroughUniversity">Warnborough University</option>
<option value="WilliamGilbertCollege">William Gilbert College</option>
<option value="WimbledonSchoolofArt">Wimbledon School of Art</option>
